import type { AccountState } from "@/shared/account-states";
export const ambassadorCopy = {
  brand: "Stena Content Portal", heading: "Ambassadörer", detailHeading: "Ambassadör", navigationLabel: "Adminnavigation", mobileNavigationLabel: "Adminmeny", rosterLink: "Ambassadörer",
  emptyHeading: "Inga ambassadörer än", emptyBody: "När ambassadörer har bjudits in visas de här.", missingName: "Namn saknas", missingValue: "Saknas", never: "Aldrig",
  name: "Namn", email: "E-post", mobile: "Mobil", state: "Kontostatus", activity: "Senaste inloggning", nextPage: "Nästa sida", invalidPage: "Sidan kunde inte visas. Gå tillbaka till ambassadörslistan.", backToRoster: "Till ambassadörslistan",
  stalePage: "Det finns inga ambassadörer kvar på den här sidan. Gå tillbaka till början av listan.",
  inviteHeading: "Bjud in ambassadör", inviteBody: "Skicka en lösenordsfri inbjudan. Vi visar när utskicket har accepterats för leverans, inte när det har levererats.",
  fullName: "Fullständigt namn", mobileOptional: "Mobil (valfritt)", inviteSubmit: "Skicka inbjudan", invitePending: "Skickar inbjudan…",
  inviteAccepted: "Inbjudan har accepterats för leverans. Leveransen är ännu inte bekräftad.", inviteFailed: "Inbjudan kunde inte skickas. Uppgifterna finns kvar så att du kan försöka igen.",
  inviteConflict: "Det finns redan ett konto med den e-postadressen.", required: "Fältet måste fyllas i.", invalidEmail: "Ange en giltig e-postadress.", invalidMobile: "Ange ett giltigt mobilnummer.", tooLong: "Värdet är för långt.",
  contactHeading: "Redigera kontaktuppgifter",
  contactDuty: "Portalen är inte kopplad till något HR-system. Administratörer ansvarar därför för att hålla namn, e-post och mobil aktuella.",
  contactSubmit: "Spara kontaktuppgifter", contactPending: "Sparar kontaktuppgifter…",
  contactSaved: "Kontaktuppgifterna har sparats.", contactFailed: "Kontaktuppgifterna kunde inte sparas. Uppgifterna finns kvar så att du kan försöka igen.",
  contactConflict: "E-postadressen används redan av ett annat konto.", contactNotFound: "Ambassadören kunde inte hittas. Ladda om sidan och försök igen.",
  lifecycleHeading: "Hantera kontoåtkomst",
  lifecycleActiveBody: "Avaktivering pausar kontot direkt och avslutar aktiva sessioner på alla enheter.",
  lifecycleDeactivatedBody: "Återaktivering ger ambassadören åtkomst igen. Befintliga sessioner avslutas inte av återaktiveringen.",
  lifecycleUnsupportedBody: "Kontoåtkomsten kan inte ändras från den här statusen.",
  deactivateSubmit: "Avaktivera konto",
  deactivateConfirm: "Jag förstår att kontot pausas direkt och att alla sessioner avslutas.",
  reactivateSubmit: "Återaktivera konto",
  lifecycleUnavailable: "Kontoåtkomst kan inte ändras",
  lifecyclePending: "Uppdaterar kontoåtkomst…",
  lifecycleDeactivated: "Kontot har avaktiverats och aktiva sessioner har avslutats.",
  lifecycleReactivated: "Kontot har återaktiverats.",
  lifecycleFailed: "Kontoåtkomsten kunde inte uppdateras. Försök igen.",
  lifecycleConflict: "Kontoåtkomsten kan inte ändras från den här statusen.",
  lifecycleNotFound: "Ambassadören kunde inte hittas. Ladda om sidan och försök igen.",
  validationFailed: "Kontrollera uppgifterna och försök igen.",
  today: "I dag", yesterday: "I går", future: "Framtida tid", daysAgo: (days: number) => `${days} dagar sedan`,
} as const;
export const accountStateCopy: Record<AccountState, string> = { invited: "Inbjuden", active: "Aktiv", inactive_declined: "Har avböjt villkor", inactive_withdrawn: "Har återkallat samtycke", deactivated: "Avaktiverad" };
export function displayOptional(value: string | null): string | null { return value?.trim() ? value : null; }
