import { beforeEach, describe, expect, it, vi } from "vitest";
const dal = vi.hoisted(() => ({ list: vi.fn(), invite: vi.fn(), requireAdmin: vi.fn() })); vi.mock("@/features/ambassadors/dal/admin", () => ({ listAmbassadors: dal.list, inviteAmbassador: dal.invite })); vi.mock("@/lib/auth", () => ({ requireAdmin: dal.requireAdmin }));
import { DomainError } from "@/lib/errors"; import { NextRequest } from "next/server"; import { GET, POST } from "./route";
describe("GET /api/ambassadors", () => { beforeEach(() => vi.clearAllMocks()); it("preserves the exact roster list envelope", async () => { dal.list.mockResolvedValue({ items: [], nextCursor: null }); const response = await GET(new NextRequest("http://local/api/ambassadors?cursor=abc")); expect(dal.list).toHaveBeenCalledWith("abc"); expect(response.status).toBe(200); expect(await response.json()).toEqual({ items: [], nextCursor: null }); }); it.each([["VALIDATION_FAILED", 422], ["AUTH_REQUIRED", 401], ["FORBIDDEN", 403]] as const)("preserves canonical GET %s mapping", async (code, status) => { dal.list.mockRejectedValue(new DomainError(code)); const response = await GET(new NextRequest("http://local/api/ambassadors")); expect(response.status).toBe(status); expect(await response.json()).toEqual({ error: { code, message: expect.any(String) } }); }); });
describe("POST /api/ambassadors", () => { beforeEach(() => { vi.clearAllMocks(); dal.requireAdmin.mockResolvedValue({ role: "admin" }); });
  it("returns normalized explicit 201", async () => { dal.invite.mockResolvedValue({ id: "id", deliveryStatus: "accepted" }); const response = await POST(new NextRequest("http://local/api/ambassadors", { method: "POST", body: JSON.stringify(input()) })); expect(response.status).toBe(201); expect(dal.invite).toHaveBeenCalledWith({ fullName: "Anna", email: "anna@example.com", mobile: null }); expect(await response.json()).toMatchObject({ deliveryStatus: "accepted" }); });
  it("returns the complete POST field-error validation envelope", async () => { const response = await POST(new NextRequest("http://local/api/ambassadors", { method: "POST", body: JSON.stringify({ fullName: "", email: "bad", mobile: "---" }) })); expect(response.status).toBe(422); expect(await response.json()).toEqual({ error: { code: "VALIDATION_FAILED", message: "Kontrollera uppgifterna och försök igen.", fields: { fullName: "Fältet måste fyllas i.", email: "Ange en giltig e-postadress.", mobile: "Ange ett giltigt mobilnummer." } } }); expect(dal.invite).not.toHaveBeenCalled(); });
  it("returns a safe 422 for malformed JSON", async () => { const response = await POST(new NextRequest("http://local/api/ambassadors", { method: "POST", body: "bad-json" })); expect(response.status).toBe(422); expect(await response.json()).toEqual({ error: { code: "VALIDATION_FAILED", message: "Kontrollera uppgifterna och försök igen." } }); expect(dal.invite).not.toHaveBeenCalled(); });
  it.each([["AUTH_REQUIRED", 401], ["FORBIDDEN", 403], ["CONFLICT", 409], ["INTERNAL_ERROR", 500]] as const)("maps %s safely", async (code, status) => { if (code === "AUTH_REQUIRED" || code === "FORBIDDEN") dal.requireAdmin.mockRejectedValue(new DomainError(code)); else dal.invite.mockRejectedValue(new DomainError(code)); const response = await POST(new NextRequest("http://local/api/ambassadors", { method: "POST", body: JSON.stringify(input()) })); expect(response.status).toBe(status); expect(await response.json()).toMatchObject({ error: { code } }); });
});
function input() { return { fullName: " Anna ", email: " ANNA@EXAMPLE.COM ", mobile: "" }; }
