import AxeBuilder from "@axe-core/playwright"; import type { Page } from "@playwright/test"; import { test, expect } from "./fixtures/auth";
async function identity(admin: Parameters<Parameters<typeof test>[1]>[0]["admin"], email: string, isAdmin: boolean) { const created = await admin.auth.admin.createUser({ email, email_confirm: true, app_metadata: isAdmin ? { admin: true } : {} }); expect(created.error).toBeNull(); expect((await admin.from("profiles").insert({ id: created.data.user!.id, email, account_state: "active" })).error).toBeNull(); return created.data.user!; }
async function login(admin: Parameters<Parameters<typeof test>[1]>[0]["admin"], page: Page, email: string) { const link = await admin.auth.admin.generateLink({ type: "magiclink", email }); expect(link.error).toBeNull(); await page.goto(`/auth/confirm?token_hash=${link.data.properties!.hashed_token}&type=magiclink&next=/admin/ambassadors`); }
test.describe.serial("ambassador invitations", () => { const ids: string[] = []; test.afterEach(async ({ admin }) => { for (const id of ids.splice(0)) await admin.auth.admin.deleteUser(id); });
  test("denies unauthorized actors before validation", async ({ admin, context, page }) => { await context.clearCookies(); expect((await page.request.post("/api/ambassadors", { data: {} })).status()).toBe(401); const user = await identity(admin, `invite-denied-${Date.now()}@example.test`, false); ids.push(user.id); await login(admin, page, user.email!); expect((await page.request.post("/api/ambassadors", { data: {} })).status()).toBe(403); });
  test("retains failures and follows the actual invitation email through confirmation", async ({ admin, clearMail, latestLink, page }) => { const administrator = await identity(admin, `invite-admin-${Date.now()}@example.test`, true); ids.push(administrator.id); await login(admin, page, administrator.email!); await page.setViewportSize({ width: 390, height: 844 }); const name = page.getByLabel("Fullständigt namn"); const emailInput = page.getByLabel("E-post"); const mobile = page.getByLabel("Mobil (valfritt)"); await name.fill("  Anna Andersson  "); await emailInput.fill("bad"); await page.getByRole("button", { name: "Skicka inbjudan" }).click(); await expect(page.getByText("Ange en giltig e-postadress.")).toBeVisible(); await expect(name).toHaveValue("  Anna Andersson  "); await expect(page.getByRole("button", { name: "Skicka inbjudan" })).toHaveCSS("min-height", "44px"); expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await page.route("**/api/ambassadors", async (route) => route.fulfill({ status: 500, body: "provider gateway failure" })); await emailInput.fill("anna@example.com"); await emailInput.blur(); await expect(page.getByText("Ange en giltig e-postadress.")).toBeHidden(); await page.getByRole("button", { name: "Skicka inbjudan" }).click(); await expect(page.getByText(/kunde inte skickas/)).toBeVisible(); await expect(name).toHaveValue("  Anna Andersson  "); await page.unroute("**/api/ambassadors");
    await clearMail(); const email = `invited-${Date.now()}@example.test`; await emailInput.fill(` ${email.toUpperCase()} `); await mobile.fill(" +46 70 000 00 00 "); await emailInput.blur(); await page.getByRole("button", { name: "Skicka inbjudan" }).click(); await expect(page.getByRole("status")).toContainText("accepterats för leverans", { timeout: 15_000 }); await expect(page.getByRole("link", { name: "Anna Andersson" })).toBeVisible(); await expect(page.locator("dd", { hasText: email })).toBeVisible(); await expect(page.locator("dd", { hasText: "+46 70 000 00 00" })).toBeVisible(); const profile = await admin.from("profiles").select("id,full_name,email,mobile,account_state,invited_at").eq("email", email).single(); expect(profile.error).toBeNull(); expect(profile.data).toMatchObject({ full_name: "Anna Andersson", email, mobile: "+46 70 000 00 00", account_state: "invited" }); expect(profile.data!.invited_at).toBeTruthy(); ids.push(profile.data!.id);
    await page.getByRole("button", { name: "Skicka inbjudan" }).click(); await expect(page.getByRole("status")).toContainText("redan ett konto"); await expect(name).toHaveValue("  Anna Andersson  "); await expect(emailInput).toHaveValue(email.toUpperCase()); await name.focus(); await expect(name).toBeFocused(); const invitedLink = await latestLink(email); const captured = new URL(invitedLink); expect(captured.pathname).toBe("/auth/confirm"); await page.goto(`${captured.pathname}${captured.search}`); await expect(page).toHaveURL(/\/auth\/consent/); });
});
