export const ERROR_HTTP_STATUS = {
  AUTH_REQUIRED: 401,
  SESSION_REVOKED: 401,
  FORBIDDEN: 403,
  ACCOUNT_INACTIVE: 403,
  NOT_FOUND: 404,
  CONSENT_REQUIRED: 409,
  CONFLICT: 409,
  UPLOAD_INCOMPLETE: 409,
  LINK_EXPIRED: 410,
  FILE_TOO_LARGE: 413,
  UNSUPPORTED_FILE_TYPE: 415,
  VALIDATION_FAILED: 422,
  BUDGET_REACHED: 429,
  RENDITION_FAILED: 500,
  EXPORT_FAILED: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_HTTP_STATUS;

export function getHttpStatus(code: ErrorCode): number {
  return ERROR_HTTP_STATUS[code];
}
