export const CONSENT_COPY = {
  eyebrow: "Stena Content Portal",
  title: "Innan du börjar",
  intro: "Läs igenom och godkänn alla tre delar för att aktivera ditt konto.",
  changedTitle: "Villkoren har ändrats",
  changedIntro: "Läs igenom de uppdaterade villkoren för att fortsätta. Delar som har ändrats är markerade.",
  changedGeneric: "Villkoren har uppdaterats. Läs igenom alla delar innan du fortsätter.",
  changedMarker: "Ändrad sedan ditt senaste godkännande",
  legalLink: "Läs hela villkorstexten",
  legalTitle: "Fullständig villkorstext",
  close: "Stäng",
  next: "Godkänn och fortsätt",
  finish: "Godkänn och aktivera konto",
  pending: "Aktiverar ditt konto …",
  reacceptFinish: "Godkänn uppdaterade villkor",
  reacceptPending: "Sparar ditt godkännande …",
  decline: "Pausa mitt konto",
  declining: "Pausar ditt konto …",
  declineError: "Kontot kunde inte pausas. Försök igen. Inget har ändrats.",
  pausedTitle: "Ditt konto är pausat",
  pausedBody: "Inget har raderats. Du kan komma tillbaka när som helst och godkänna villkoren för att aktivera kontot igen.",
  pausedReturn: "Gå tillbaka till villkoren",
  deactivatedTitle: "Ditt konto är pausat",
  deactivatedBody: "Kontakta en administratör om du behöver hjälp med att återfå åtkomst.",
  position: (current: number, total: number) => `Del ${current} av ${total}`,
  unavailableTitle: "Villkoren kan inte visas just nu",
  unavailableBody: "Försök igen om en liten stund. Kontakta HR om problemet kvarstår. Inget har sparats.",
  retry: "Försök igen",
  submitError: "Kontot kunde inte aktiveras. Försök igen. Inget ofullständigt godkännande har sparats.",
  tasksTitle: "Dina uppdrag",
  tasksEmpty: "Det finns inga uppdrag att visa ännu.",
} as const;
