import { randomBytes, randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { decryptIdentity, encryptIdentity, headPayload, keyFromBase64, recordPayload, signHead, signRecord, verifyHexHmac, ZERO_HMAC } from "./crypto";
const key = randomBytes(32).toString("base64");
describe("consent cryptography", () => {
  it("uses the specified fixed-order canonical payloads", () => { const id = randomUUID(); const at = new Date("2026-07-16T10:00:00Z"); expect(JSON.parse(recordPayload({ chainPosition: 1n, recordId: id.toUpperCase(), recordType: "acceptance", userIdSnapshot: id, termsVersionId: id, termsPayloadSha256: "A".repeat(64), occurredAt: at, prevHmac: ZERO_HMAC }))).toEqual(["acceptance-record-v1", "1", id, "acceptance", id, id, "a".repeat(64), "2026-07-16T10:00:00.000Z", ZERO_HMAC]); expect(JSON.parse(headPayload(1n, "A".repeat(64)))[0]).toBe("acceptance-chain-head-v1"); });
  it("signs records and heads", () => { const id = randomUUID(); const record = { chainPosition: 1n, recordId: id, recordType: "acceptance" as const, userIdSnapshot: id, termsVersionId: id, termsPayloadSha256: "a".repeat(64), occurredAt: new Date(), prevHmac: ZERO_HMAC }; expect(verifyHexHmac(signRecord(record, key), signRecord(record, key))).toBe(true); expect(signHead(1n, signRecord(record, key), key)).toHaveLength(64); });
  it("preserves canonical bigint positions above MAX_SAFE_INTEGER", () => { const id = randomUUID(); const position = 9007199254740993n; expect(JSON.parse(recordPayload({ chainPosition: position, recordId: id, recordType: "acceptance", userIdSnapshot: id, termsVersionId: id, termsPayloadSha256: "a".repeat(64), occurredAt: "2026-07-16T10:00:00.000Z", prevHmac: ZERO_HMAC }))[1]).toBe("9007199254740993"); expect(JSON.parse(headPayload(position, ZERO_HMAC))[1]).toBe("9007199254740993"); });
  it("round trips identity with record/user-bound AAD and rejects swaps", () => { const user = randomUUID(), record = randomUUID(); const envelope = encryptIdentity(user, record, { email: "synthetic@example.test", fullName: "Synthetic User" }, key); expect(decryptIdentity(user, record, envelope.identity, envelope.wrappedKey, key).email).toBe("synthetic@example.test"); expect(() => decryptIdentity(user, randomUUID(), envelope.identity, envelope.wrappedKey, key)).toThrow(); });
  it.each(["", "junk", `${key}junk`, key.slice(0, -1)])("rejects non-canonical key %j", (value) => { expect(() => keyFromBase64("TEST_KEY", value)).toThrow(/TEST_KEY/); });
});
