"use client";
import { useMutation } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useRef, useState, type FormEvent } from "react";
import { ambassadorCopy } from "../copy";
import { inviteAmbassadorSchema } from "../schemas/invite-ambassador";
type Field = "fullName" | "email" | "mobile"; type Values = Record<Field, string>; type FieldErrors = Partial<Record<Field, string>>; type InviteResponse = { deliveryStatus: "accepted" };
class InviteRequestError extends Error { constructor(readonly code?: string, readonly fields?: FieldErrors) { super("Invite request failed"); } }
async function sendInvite(values: Values): Promise<InviteResponse> { const response = await fetch("/api/ambassadors", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); const text = await response.text(); let body: { deliveryStatus?: unknown; error?: { code?: string; fields?: FieldErrors } } = {}; try { body = text ? JSON.parse(text) : {}; } catch { throw new InviteRequestError(); } if (!response.ok) throw new InviteRequestError(body.error?.code, body.error?.fields); if (body.deliveryStatus !== "accepted") throw new InviteRequestError(); return { deliveryStatus: "accepted" }; }
export function InviteForm() {
  const router = useRouter(); const submitting = useRef(false); const [values, setValues] = useState<Values>({ fullName: "", email: "", mobile: "" }); const [errors, setErrors] = useState<FieldErrors>({});
  const mutation = useMutation({ mutationFn: sendInvite, onSuccess: (result) => { if (result.deliveryStatus === "accepted") router.refresh(); }, onSettled: () => { submitting.current = false; } });
  const validate = () => { const result = inviteAmbassadorSchema.safeParse(values); const next: FieldErrors = {}; if (!result.success) for (const issue of result.error.issues) { const field = issue.path[0] as Field; if (field in values) next[field] ??= issue.message; } return next; };
  const submit = (event: FormEvent) => { event.preventDefault(); if (submitting.current) return; const next = validate(); setErrors(next); if (Object.keys(next).length) { const firstInvalid = (["fullName", "email", "mobile"] as const).find((field) => next[field]); if (firstInvalid) document.getElementById(`invite-${firstInvalid}`)?.focus(); return; } submitting.current = true; mutation.mutate(values, { onError: (error) => setErrors(error instanceof InviteRequestError ? error.fields ?? {} : {}) }); };
  const failure = mutation.error instanceof InviteRequestError ? mutation.error : null; const fields = [["fullName", ambassadorCopy.fullName, "text"], ["email", ambassadorCopy.email, "email"], ["mobile", ambassadorCopy.mobileOptional, "tel"]] as const;
  return <section aria-labelledby="invite-heading" className="mb-8 rounded bg-[#eae3d2] p-6"><h2 className="text-xl font-semibold" id="invite-heading">{ambassadorCopy.inviteHeading}</h2><p className="mt-2 max-w-2xl">{ambassadorCopy.inviteBody}</p><form className="mt-5 grid max-w-xl gap-4" noValidate onSubmit={submit}>{fields.map(([field, label, type]) => <div key={field}><label className="block font-semibold" htmlFor={`invite-${field}`}>{label}</label><input aria-describedby={errors[field] ? `invite-${field}-error` : undefined} aria-invalid={Boolean(errors[field])} className="mt-1 min-h-11 w-full rounded border border-black bg-white px-3 text-base focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#3344dd]" id={`invite-${field}`} onBlur={() => setErrors((current) => ({ ...current, [field]: validate()[field] }))} onChange={(event) => { if (!mutation.isPending) mutation.reset(); setValues((current) => ({ ...current, [field]: event.target.value })); }} type={type} value={values[field]} />{errors[field] ? <p className="mt-1 border-l-4 border-[#e41f1f] pl-2 text-black" id={`invite-${field}-error`}>{errors[field]}</p> : null}</div>)}<button className="min-h-11 rounded bg-[#034592] px-4 py-2 font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#3344dd] disabled:opacity-60" disabled={mutation.isPending} type="submit">{mutation.isPending ? ambassadorCopy.invitePending : ambassadorCopy.inviteSubmit}</button><div aria-live="polite" role="status">{mutation.isSuccess ? ambassadorCopy.inviteAccepted : mutation.isError ? (failure?.code === "CONFLICT" ? ambassadorCopy.inviteConflict : ambassadorCopy.inviteFailed) : null}</div></form></section>;
}
