// @vitest-environment jsdom
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"; import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"; import { afterEach, describe, expect, it, vi } from "vitest";
const refresh = vi.hoisted(() => vi.fn()); vi.mock("next/navigation", () => ({ useRouter: () => ({ refresh }) })); import { InviteForm } from "./invite-form";
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.clearAllMocks(); }); function setup() { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { mutations: { retry: false } } })}><InviteForm /></QueryClientProvider>); }
describe("InviteForm", () => {
  it("validates on blur and retains every value after duplicate failure", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, text: async () => JSON.stringify({ error: { code: "CONFLICT" } }) })); setup(); fireEvent.blur(screen.getByLabelText("Fullständigt namn")); expect(await screen.findByText("Fältet måste fyllas i.")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Fullständigt namn"), { target: { value: "Anna" } }); fireEvent.change(screen.getByLabelText("E-post"), { target: { value: "anna@example.com" } }); fireEvent.change(screen.getByLabelText("Mobil (valfritt)"), { target: { value: "+46 70 123 45 67" } }); fireEvent.click(screen.getByRole("button")); expect(await screen.findByText(/redan ett konto/)).toBeTruthy(); expect((screen.getByLabelText("Fullständigt namn") as HTMLInputElement).value).toBe("Anna"); expect((screen.getByLabelText("E-post") as HTMLInputElement).value).toBe("anna@example.com"); expect((screen.getByLabelText("Mobil (valfritt)") as HTMLInputElement).value).toBe("+46 70 123 45 67"); });
  it("deduplicates pending submission and refreshes only for explicit accepted status", async () => { let resolve!: (value: unknown) => void; const fetchMock = vi.fn(() => new Promise((done) => { resolve = done; })); vi.stubGlobal("fetch", fetchMock); setup(); fill(); fireEvent.click(screen.getByRole("button")); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(1)); fireEvent.submit(screen.getByRole("button").closest("form")!); expect(fetchMock).toHaveBeenCalledTimes(1); expect(refresh).not.toHaveBeenCalled(); resolve({ ok: true, text: async () => JSON.stringify({ deliveryStatus: "accepted" }) }); await waitFor(() => expect(refresh).toHaveBeenCalledTimes(1)); });
  it("stops announcing a settled invite once the admin edits the form again", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: true, text: async () => JSON.stringify({ deliveryStatus: "accepted" }) })); setup(); fill(); fireEvent.click(screen.getByRole("button")); await waitFor(() => expect(screen.getByRole("status").textContent).toContain("accepterats för leverans")); fireEvent.change(screen.getByLabelText("Fullständigt namn"), { target: { value: "Bo" } }); await waitFor(() => expect(screen.getByRole("status").textContent).toBe("")); });
  it("handles non-JSON failure safely without refresh or lost input", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, text: async () => "gateway html" })); setup(); fill(); fireEvent.click(screen.getByRole("button")); expect(await screen.findByText(/kunde inte skickas/)).toBeTruthy(); expect(refresh).not.toHaveBeenCalled(); expect((screen.getByLabelText("E-post") as HTMLInputElement).value).toBe("anna@example.com"); });
});
function fill() { fireEvent.change(screen.getByLabelText("Fullständigt namn"), { target: { value: "Anna" } }); fireEvent.change(screen.getByLabelText("E-post"), { target: { value: "anna@example.com" } }); }
